server:
  port: 8080
  servlet:
    context-path: /

amazon:
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    dynamodb:
      endpoint: ${AWS_DYNAMODB_ENDPOINT}
