name: Build and Deploy AWS

on:
  workflow_run:
    workflows: ["Docker Build And Deploy to AWS ECR"]
    types:
      - completed

jobs:
  build_aws:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Find directory
        run: ls

      - name: Deploy to AWS
        run: |
          pwd
          whoami
          ls -al
          chmod +x ./deploy.sh
          ./deploy.sh

      - name: Deployment successful
        if: success()
        run: echo 'Deployment successful!'