name: Destroy Infra terraform AWS

on:
  push:
    branches:
      - rollback/*
  pull_request:
    branches:
      - rollback/*

jobs:
  build_aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configuration AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Find directory
        run: ls

      - name: Destroy AWS
        run: |
          pwd
          whoami
          ls -al
          chmod +x ./destroy.sh
          ./destroy.sh

      - name: Destroy realizado com sucesso
        if: success()
        run: echo 'Destroy successful!'